# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8df1e23f4a76379a82945fcf7b957eb1c032c7e2400498ae6f11dad32c594c850c9eb254e0aa7cd2a570c1fd77299bbb511c92369113baf9580e3229923295d

test:
  secret_key_base: 1b16c87eac65fb7e8185d4a76b234c92dd552a0fd408c40f39d44f2f17da35059132fbdd65dd1ac5b2229a7771ee14bfdea8664a4b523cf7d7e3739390c6e988

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
